# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
additionalRepositories:
  - url: https://github.com/WebstoneHQ/webstone-education
    checkoutLocation: webstone-education

checkoutLocation: ./course

workspaceLocation: ./course/.code-workspace

tasks:
  - before: |
      npm i -g pnpm
    init: |
      node ./scripts/symlink-course.js
      cd ../webstone-education
      node ./app/scripts/symlink-course.js
      pnpm install
    command: |
      gp sync-done pnpm-install
      cd ../webstone-education
      pnpm start
  - command: |
      gp sync-await pnpm-install
      cd ../webstone-education
      pnpm dev